title: Amara Oinam
description: Adventurer, artist

remote_theme: oinam/oinam-jekyll

footer:
  custom: true

footer_custom: "All Rights Reserved. Amara."

styles:
  forms: false
  syntax_highlighter: false